let car = 'subaru'
console.log("Is car == 'subaru'? I predict True.")
console.log(car == 'subaru')
console.log("Is car === 'Subaru'? I predict False.")
console.log(car === 'Subaru')
console.log("Is car != 'toyota'? I predict True.")
console.log(car != 'toyota')
console.log("Is car !== 'subaru'? I predict False.")
console.log(car !== 'subaru')
console.log("Is car.length == 6? I predict True.")
console.log(car.length == 6)
console.log("Is car.toUpperCase() == 'SUBARU'? I predict True.")
console.log(car.toUpperCase() == 'SUBARU')
console.log("Does car include 'bar'? I predict True.")
console.log(car.includes('bar'))
console.log("Is car.length > 10? I predict False.")
console.log(car.length > 10)
console.log("Is 'Subaru'.toLowerCase() == car? I predict True.")
console.log('Subaru'.toLowerCase() == car)
console.log("Is car.concat('s') == 'subarus'? I predict True.")
console.log(car.concat('s') == 'subarus')